git:
  commit: true
  commitMessage: 'chore: release ${version}'
  tag: true
  tagName: 'v${version}'
  requireCleanWorkingDir: true
github:
  release: true
  releaseName": 'v${version}'
hooks:
  before:init:
    - 'yarn run test'
  after:bump:
    - 'yarn run build'
  after:release:
    - 'echo Successfully released ${name} v${version} to ${repo.repository}.'
plugins:
  '@release-it/conventional-changelog':
    preset: 'angular'
    infile: 'CHANGELOG.md'
